# GitHub Actions Cache Configuration
# This file is used to configure cache strategy and optimize build performance

cache_strategies:
  # GitHub Actions Cache Configuration
# This file is used to configure cache strategy and optimize build performance

# ESP-IDF toolchain cache
esp_idf:
  key_prefix: "esp-idf"
  paths:
    - "C:\\esp-idf"
    - "C:\\esp-idf-tools"
  version: "v4.4.6"
  max_age: 604800  # 7 days

# CMake cache
cmake:
  key_prefix: "cmake"
  paths:
    - "C:\\Program Files\\CMake"
    - "C:\\CMake"
  version: "3.21.0"
  max_age: 604800  # 7 days

# Ninja build tool cache
ninja:
  key_prefix: "ninja"
  paths:
    - "C:\\ninja"
  version: "1.10.0"
  max_age: 604800  # 7 days

# Python packages cache
python:
  key_prefix: "python"
  paths:
    - "~\\AppData\\Local\\pip\\Cache"
  max_age: 259200  # 3 days

# Build cache
build_cache:
  key_prefix: "build"
  paths:
    - "build/_deps"
    - "build/CMakeFiles"
    - "build/esp-idf"
  max_age: 86400  # 1 day

# Cache optimization suggestions
optimization:
  - "Use restore-keys to improve cache hit rate"
  - "Use separate cache keys for different tools"
  - "Regularly update cache key versions"
  - "Monitor cache size to avoid exceeding limits"