# nanoFramework ESP32 Build Configuration
# This file contains build parameters and settings for ESP32 targets

# Default build configuration
defaults:
  target_board: "ESP32_WROOM_32"
  build_type: "Release"
  debug_enabled: false

# Supported ESP32 targets as per nanoFramework documentation
supported_targets:
  ESP32_WROOM_32:
    description: "ESP32-WROOM-32 module with 4MB flash"
    idf_target: "esp32"
    toolchain_prefix: "xtensa-esp32-elf"
  ESP32_WROVER_KIT:
    description: "ESP32-WROVER-KIT development board"
    idf_target: "esp32"
    toolchain_prefix: "xtensa-esp32-elf"
  ESP32_PICO:
    description: "ESP32-PICO-D4 module"
    idf_target: "esp32"
    toolchain_prefix: "xtensa-esp32-elf"
  ESP32_S2:
    description: "ESP32-S2 series"
    idf_target: "esp32s2"
    toolchain_prefix: "xtensa-esp32s2-elf"
  ESP32_C3:
    description: "ESP32-C3 series (RISC-V)"
    idf_target: "esp32c3"
    toolchain_prefix: "riscv32-esp-elf"

# Tool versions (matching nanoFramework requirements)
tool_versions:
  esp_idf: "v4.4.6"
  cmake: "3.21.0"
  ninja: "1.10.0"
  python: "3.8"

# Core APIs enabled by default
core_apis:
  - API_System.Device.Gpio=ON
  - API_System.Device.Spi=ON
  - API_System.Device.I2c=ON
  - API_System.Device.Pwm=ON
  - API_System.Device.SerialCommunication=ON
  - API_Windows.Devices.Gpio=ON
  - API_Windows.Devices.Spi=ON
  - API_Windows.Devices.I2c=ON
  - API_Windows.Devices.Pwm=ON
  - API_Windows.Devices.SerialCommunication=ON
  - API_nanoFramework.ResourceManager=ON
  - API_nanoFramework.System.Collections=ON
  - API_nanoFramework.System.Text=ON

# Optional features (can be enabled as needed)
optional_features:
  networking:
    - API_System.Net=ON
    - API_System.Net.Http=ON
    - API_System.Net.WebSockets=ON
    - API_System.Net.WebSockets.Client=ON
  wifi:
    - API_System.Device.Wifi=ON
  hardware:
    - API_System.Device.Adc=ON
    - API_System.Device.Dac=ON
    - API_Hardware.Esp32=ON
    - API_nanoFramework.Hardware.Esp32.Rmt=ON
    - API_nanoFramework.Hardware.Esp32.Ble=ON
  filesystem:
    - API_nanoFramework.System.IO.FileSystem=ON
    - API_nanoFramework.System.IO.Streams=ON
  time:
    - API_nanoFramework.Networking.Sntp=ON

# Build optimization settings
build_options:
  # Memory optimization
  memory:
    - "CONFIG_COMPILER_OPTIMIZATION_SIZE=y"
    - "CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_DISABLE=y"
  
  # Debug settings
  debug:
    enabled: false
    symbols: true
    optimization: "CONFIG_COMPILER_OPTIMIZATION_DEBUG=y"

# Cache configuration for GitHub Actions
cache:
  esp_idf:
    key_prefix: "esp-idf"
    paths:
      - "C:\\esp-idf"
      - "C:\\esp-idf-tools"
    max_age: 604800  # 7 days
  
  cmake:
    key_prefix: "cmake"
    paths:
      - "C:\\Program Files\\CMake"
    max_age: 604800  # 7 days
  
  ninja:
    key_prefix: "ninja"
    paths:
      - "C:\\ninja"
    max_age: 604800  # 7 days

# Environment variables
environment:
  ESP_IDF_PATH: "C:\\esp-idf"
  IDF_TOOLS_PATH: "C:\\esp-idf\\tools"
  IDF_TARGET: "esp32"

# Build artifacts configuration
artifacts:
  firmware:
    include:
      - "*.bin"
      - "*.hex"
      - "*.elf"
    exclude:
      - "*.map"
      - "*.lst"
  retention_days: 30

# Validation rules
validation:
  required_tools:
    - cmake
    - ninja
    - python
    - xtensa-esp32-elf-gcc
  
  board_validation:
    check_idf_support: true
    validate_pins: true